# Generated by Django 4.2.3 on 2023-08-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
